// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk3gPze6BT8Zj4lI1EhZ5nM46r7sCmGCk',
    appId: '1:583028735091:web:6e6095d6a8b7ac251b7e06',
    messagingSenderId: '583028735091',
    projectId: 'feedback-form-a0e23',
    authDomain: 'feedback-form-a0e23.firebaseapp.com',
    storageBucket: 'feedback-form-a0e23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxTwASld4SIfJEwdIm7lGT_xXPJ0jDnd0',
    appId: '1:583028735091:android:81797294ec9d01d31b7e06',
    messagingSenderId: '583028735091',
    projectId: 'feedback-form-a0e23',
    storageBucket: 'feedback-form-a0e23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxiCy2iwwa8njTYbMiX_eLQdj8Z316dQE',
    appId: '1:583028735091:ios:bf693dea501d74f91b7e06',
    messagingSenderId: '583028735091',
    projectId: 'feedback-form-a0e23',
    storageBucket: 'feedback-form-a0e23.appspot.com',
    iosClientId: '583028735091-1400n5faljvs523lc2bsu8aancsvictm.apps.googleusercontent.com',
    iosBundleId: 'fozycom.de.learnTigrignaApp',
  );
}
